services:
  flask:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: flask
    ports:
      - "8000:8000"
    depends_on:
      - app-postgres
    volumes:
      - ~/.uploads/images/flask-yt:/app/app/static/upload
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: wallets_db
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: app-postgres
      POSTGRES_PORT: 5432
    expose:
      - 8080

  app-postgres:
    image: postgres:16
    container_name: postgres_2
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ~/.pg/pg_data/flask-yt:/var/lib/postgresql/data

  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "pytest", "-v" ]
    volumes:
      - .:/app
    env_file:
      - .env.docker
    environment:
      - ENV=test
      - DATABASE_URL=postgresql://admin_db:password@app-postgres:5432/wallets_db
    depends_on:
      - app-postgres

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx/
    container_name: nginx
    env_file:
      - .env.docker
    depends_on:
      - flask
    ports:
      - "8080:80"